[package]
name = "main-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tunnel-proto = { path = "../tunnel-proto" }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dashmap = { workspace = true }
axum = { workspace = true }
tokio-stream = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true }
